### ISSUE TITLE
FORGET/DELETE operation fails

### ISSUE THREAD

**Issue by anatol** [bfleischer/macfuse#3] opened 2011-05-11 16:00 UTC
This is a command that I use for testing your changes:
# It assumes that 'pkg-config --libs fuse' works fine

$ git clone git://github.com/anatol/tup.git && cd tup && git checkout fuse && ./bootstrap.sh

It works with the latest official release (+macports patches) but fails with your master:

[    0/17   ] src/tup/CC create_name_file.c
unique: 11, opcode: ACCESS (34), nodeid: 1, insize: 48
access / 01
   unique: 11, success, outsize: 16
unique: 11, opcode: LOOKUP (1), nodeid: 1, insize: 46
LOOKUP /Users
getattr /Users
   NODEID: 2
   unique: 11, success, outsize: 152
unique: 12, opcode: FORGET (2), nodeid: 2, insize: 48
FORGET 2/1
DELETE: 2
Users/anatol/sources/tup: Invalid argument

I guess that something wrong with the DELETE.

**Comment by bfleischer** [comment] 2011-05-11 17:02
At the moment I'm working on CREATE (which does not work as expected either), but I will take a closer look as soon as possible. The Illegal Argument error you are seeing is most likely caused by an incompatibility of the current MacFUSE kext and libfuse 2.8.5 (different versions of fuse-kernel.h are used).

I assume your command/test works on the macfuse-2.1 branch (meaning MacFUSE 2.1.11). If not, please let me know.

**Comment by bfleischer** [comment] 2011-05-12 02:07
I did some more testing with the official MacFUSE releases 2.0.3 and 2.1.5, my MacFUSE 2.1.11 release and the master branch but "./build/tup upd --debug-fuse" failed every time.

I alway got something like this:

unique: 5, opcode: ACCESS (34), nodeid: 1, insize: 48
ACCESS / 01
   unique: 5, error: 0 (Unknown error: 0), outsize: 16
unique: 5, opcode: LOOKUP (1), nodeid: 1, insize: 46
LOOKUP /Users
   NODEID: 2
   unique: 5, error: 0 (Unknown error: 0), outsize: 152
Users/benjamin/tup: Invalid argument
unique: 6, opcode: FORGET (2), nodeid: 2, insize: 48
FORGET 2/1
delete: 2
 **\* Command 708 failed with return value 1: gcc -c bin.c -o bin.o -Os -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Wwrite-strings -fno-common -I../../src `pkg-config fuse --cflags` -DAT_SYMLINK_NOFOLLOW=0x100 -DAT_FDCWD=-100

**Comment by anatol** [comment] 2011-05-12 02:22
This is the error that I've had with clean 2.1.11 as well. It is what confused me as tup compiles fine with 2.0.3 version from macports. https://trac.macports.org/browser/trunk/dports/fuse/macfuse

Tomorrow I'll try to test it more.

**Comment by bfleischer** [comment] 2011-05-12 18:33
It took me quite some time but I figured it out. There are two bugs involved, one in tup and the other one in the MacPorts version of MacFUSE 2.0.3.
- MacPorts version of MacFUSE 2.0.3 (2.0.3 revision 4)

The MacPorts patch for libfuse (patch-10.6_libfuse_fuse-2.7.3-macosx.patch.diff) changes CFLAGS to:

```
CFLAGS="-D__FreeBSD__=10 -D_POSIX_C_SOURCE=200112L -I$MACFUSE_SRCROOT/common -O -gdwarf-2 -arch i386 -arch x86_64 -isysroot /Developer/SDKs/MacOSX10.6.sdk" LDFLAGS="-arch i386 -arch x86_64  -framework CoreFoundation" ./configure --prefix=@@PREFIX@@ --disable-dependency-tracking --disable-static --with-libiconv-prefix=@@PREFIX@@
```

The 10.6 SDK defaults to a 64 bit stat structure whereas the 10.5 SDK defaults to a 32 bit stat structure. The MacPorts patch just replaces
`-isysroot /Developer/SDKs/MacOSX10.5.sdk`
with
`-isysroot /Developer/SDKs/MacOSX10.6.sdk`
without taking that into account. In the end you get a FUSE library requiring a filesystem to use the 64 bit stat structure instead of the default 32 bit structure. Obviously this leads to incompatibilities.

This can be fixed by adding `-D__DARWIN_64_BIT_INO_T=0` to CFLAGS.
- tup

The bootstrap script compiles the tup source against the default SDK (10.6 on Snow Leopard) without setting `-D__DARWIN_64_BIT_INO_T=0`. The result is a filesystem that is incompatible with official MacFUSE releases. This can be fixed by replacing line 24 of the bootstrap script with

```
plat_cflags="$plat_cflags -D__DARWIN_64_BIT_INO_T=0 -DAT_SYMLINK_NOFOLLOW=0x100"
```

All in all this is not a MacFUSE bug.

**Closed as completed by bfleischer** 2011-05-12 18:33 UTC

**Comment by anatol** [comment] 2011-05-12 19:44
Bingo! Thanks Benjamin, your advice fixed the issue (although I see another one that I am going to look at).

If any app that uses macfuse requires this flag would it be better to add it to fuse.pc file? https://github.com/bfleischer/fuse/blob/fuse-2.7.3-macfuse/fuse.pc.in

**Comment by bfleischer** [comment] 2011-05-12 19:57
Thought about that too. Seems reasonable to me. But for libfuse_ino64 we would need `-D__DARWIN_64_BIT_INO_T=1`

Is the other issue related to the op UNLINK with branch master (MacFUSE 2.2.0)? tup worked fine for me with MacFUSE 2.1.11 after the patching as described above.

**Comment by bfleischer** [comment] 2011-05-12 21:12
I added `-D__DARWIN_64_BIT_INO_T=0` to fuse.pc.in (libfuse 2.7.3 and 2.8.5)

**Comment by anatol** [comment] 2011-05-13 16:33
<pre>But for libfuse_ino64 we would need -D__DARWIN_64_BIT_INO_T=1</pre>


Because 64bits inodes are default for 10.6, would it be better for this version to have 2 *.pc files: libfuse.pc (defaults with 64 bit inodes) and libfuse_i32.pc (with -D__DARWIN_64_BIT_INO_T=0) ? For backward compatibility it is possible to add libfuse_i64.pc that is symlinked with the default version.

**Comment by anatol** [comment] 2011-05-14 00:32
But if 64bits inodes are default on 10.6 would it be better to have fuse.pc & fuse_i32.pc instead? Where fuse.pc has flags by default and i32 has -D__DARWIN_64_BIT_INO_T=0?

**Comment by bfleischer** [comment] 2011-05-14 13:20
I'm not sure where I read it but there was a understanding that libfuse should alway stick to 32 bit inodes to remain compatible with filesystems compiled against an earlier version of libfuse. Changing behavior to let fuse.pc point to the ino64 version of libfuse might be an option but would make the resulting filesystem incompatible with earlier versions of MacFUSE/Mac OS X, where there is not ino64 version of the library.

In commit 462e83c796b5b54d461d8125db73349974b55a02 I patched the libfuse build process to create an additional package config file for libfuse_ino64 (fuse_ino64.pc). Now everything should be according to conventions, I hope. At least it is consistent.
